import './globals.css';

import type { Metadata } from 'next';

import { MSWProvider } from '@/app/MSWProvider';
import ReactQueryProvider from '@/app/ReactQueryProvider';
import RecoilRootProvider from '@/app/RecoilRootProvider';
import { initMSW } from '@/mocks';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

if (process.env.NODE_ENV === 'development') {
  initMSW();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProvider>
          <RecoilRootProvider>
            <MSWProvider>{children}</MSWProvider>
          </RecoilRootProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
