import './globals.css';

import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';

import { MSWProvider } from '@/app/MSWProvider';
import ReactQueryProvider from '@/app/ReactQueryProvider';
import RecoilRootProvider from '@/app/RecoilRootProvider';
import { initMSW } from '@/mocks';

const notoSansKr = Noto_Sans_KR({
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

if (process.env.NODE_ENV === 'development') {
  initMSW();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={notoSansKr.className}>
        <ReactQueryProvider>
          <RecoilRootProvider>
            <MSWProvider>{children}</MSWProvider>
          </RecoilRootProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
